
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerized-api-deployment
  labels:
        app: dockerized-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockerized-api
  template:
    metadata:
      labels:
        app: dockerized-api
    spec:
      containers:
        - name: dockerized-api
          image: 872898460552.dkr.ecr.us-east-1.amazonaws.com/dockerize:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080