apiVersion: v1
kind: Service
metadata:
  name: dockerized-api-service
spec:
  selector:
    app: dockerized-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
    
  type: LoadBalancer
